@url = http://localhost:5036


###
GET {{url}}

###
GET {{url}}/reservations


###
POST {{url}}/reservations
Content-Type: application/json

{
    "BookerName": "Kamil Matusz",
    "ParkinSpotName" : "P1",
    "LicensePlate" : "XYZ123",
}

